#! /usr/bin/env python
import socket, sys

def main(args):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    host = socket.gethostbyname(args[1])

    s.connect((host, int(args[2])))

    s.send("GET / HTTP/1.0\r\n\r\n")

    reply = s.recv(4096)

    print reply

if __name__ == '__main__':
   main(sys.argv)
